//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class members_g_wechat_staging
    {
        public int Id { get; set; }
        public int AppType { get; set; }
        public string OpenId { get; set; }
        public string UnionId { get; set; }
        public Nullable<bool> Subscribe { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Language { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string HeadimgUrl { get; set; }
        public Nullable<int> SubscribeTime { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string TagIdList { get; set; }
        public string SubscribeScene { get; set; }
        public Nullable<int> QRScene { get; set; }
        public string QRSceneStr { get; set; }
        public string Remark { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
